[package]
name = "aambient"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
display-info = "0.4.1"
nokhwa = "0.10.3"
screenshots = "0.5.2"
